now:
	python3 ooclassifierbasev3.py data.v1
	python3 ooclassifierbasev3.py header.v1 data.v1.noheader
	python3 ooclassifierbasev3.py helpdata_real.v1

old3:
	python3 ooclassifierbasev2.py data.v1
	python3 ooclassifierbasev2.py header.v1 data.v1.noheader
	python3 ooclassifierbasev2.py helpdata.v1

old2:
	python3 ooclassifierbasev2.py data.v1

base:
	python3 ooclassifierbase.py data.v1

old:
	python3 ooclassifierlecture.v1.py data.v1

style:
	python3 ~/arduino-ua/bin/stylecheck.py ooclassifierbasev2.py
