now:	
	echo "sample0"
	echo
	python3 freq.py sample_data/sample0
	echo "sample1"
	echo
	python3 freq.py sample_data/sample1
	echo "sample2"
	echo 
	python3 freq.py sample_data/sample2
	echo "sample4"
	echo
	python3 freq.py sample_data/sample4
	echo "Error case"
	echo
	python3 freq.py hello hello
