now:
	echo "cmd 1"
	cat words.2 | python3 split.line.p5.v1.py | python3 count.the.p4.v1.py
	echo "cmd 2"
	python3 split.line.p5.v1.py < words.2 | python3 count.the.p4.v1.py
	echo "cmd 3"
	grep e words.2 | python3 split.line.p5.v1.py | python3 count.the.p4.v1.py	
	echo "cmd 4"
	cat words.2 | python3 count.the.p4.v1.py
	echo "cmd 5"
	grep e words.2 | python3 count.the.p4.v1.py
